import { PGlite } from "@electric-sql/pglite";
import { Orm, PostgresDialect, createPostgresExecutor } from "metal-orm";

let db: PGlite | null = null;
let orm: Orm | null = null;

async function execSql(database: PGlite, sql: string, params?: unknown[]): Promise<void> {
  await database.query(sql, params);
}

export async function initializeDatabase() {
  db = new PGlite();
  await execSql(
    db,
    `
    create table users (
      id integer generated by default as identity primary key,
      name text not null,
      email text,
      createdAt timestamp not null
    )
    `
  );
  await execSql(
    db,
    `
    create table posts (
      id integer generated by default as identity primary key,
      title text not null,
      body text,
      userId integer not null,
      createdAt timestamp not null,
      foreign key(userId) references users(id)
    )
    `
  );

  await execSql(db, `
    INSERT INTO users (name, email, createdAt) VALUES 
      ('Alice', 'alice@example.com', TIMESTAMP '2026-01-17 00:00:00'),
      ('Bob', 'bob@example.com', TIMESTAMP '2026-01-17 00:00:00')
  `);

  await execSql(db, `
    INSERT INTO posts (title, body, userId, createdAt) VALUES 
      ('First Post', 'This is the first post content', 1, TIMESTAMP '2026-01-17 00:00:00'),
      ('Second Post', 'Another post here', 2, TIMESTAMP '2026-01-17 00:00:00'),
      ('Third Post', 'Yet another post', 1, TIMESTAMP '2026-01-17 00:00:00')
  `);

  const executor = createPostgresExecutor(db);
  orm = new Orm({
    dialect: new PostgresDialect(),
    executorFactory: {
      createExecutor: () => executor,
      createTransactionalExecutor: () => executor,
      dispose: async () => {}
    }
  });
}

export function createSession() {
  if (!orm) {
    throw new Error("ORM not initialized");
  }
  return orm.createSession();
}
