// adorn.config.ts
// Configuration file for adorn-api code generators

import type { AdornConfig } from "./src/lib/config.js";

const config: AdornConfig = {
  // Project configuration
  tsConfig: "./tsconfig.json",
  
  // Controller discovery
  controllersGlob: "tests/example-app/controllers/**/*.ts",
  
  // Route generation
  routesOutput: "./tests/example-app/routes.ts",
  basePath: "", // Optional global base path (e.g., "/api/v1")
  
  // Swagger generation
  swaggerOutput: "./swagger.json",
  swaggerInfo: {
    title: "Adorn API",
    version: "2.0.0",
    description: "API documentation generated by adorn-api",
  },
  
  // Middleware paths (relative to output directory)
  authMiddlewarePath: "./middleware/auth.middleware.js",
};

export default config;
