/* tslint:disable */
/* eslint-disable */
// WARNING: This file was auto-generated by adorn-api. Do not edit.
import { Express, Request, Response, NextFunction } from 'express';
import { DefaultAuthAdapter, ClassInstantiatingDTOFactory, DefaultErrorAdapter } from 'adorn-api';
import multer from 'multer';
import { ExampleController } from './controllers/example.controller.js';

export function RegisterRoutes(app: Express) {
    
    
    app.get('/api/users', [], async (req: Request, res: Response, next: NextFunction) => {
        const controller = new ExampleController();
        
        // Initialize adapters
        const errorAdapter = new DefaultErrorAdapter();
        
        try {
            
            const response = await controller.getAllUsers();
            res.status(200).json(response);
        } catch (err: any) {
            const transformedError = errorAdapter.handleError(err);
            next(transformedError);
        }
    });
    
    app.get('/api/users/:id', [], async (req: Request, res: Response, next: NextFunction) => {
        const controller = new ExampleController();
        
        // Initialize adapters
        const errorAdapter = new DefaultErrorAdapter();
        
        try {
            
        const id = (req.body as any)?.id || (req.params as any)?.id || (req.query as any)?.id;

            const response = await controller.getUserById(id);
            res.status(200).json(response);
        } catch (err: any) {
            const transformedError = errorAdapter.handleError(err);
            next(transformedError);
        }
    });
    
    app.post('/api/users', [], async (req: Request, res: Response, next: NextFunction) => {
        const controller = new ExampleController();
        
        // Initialize adapters
        const errorAdapter = new DefaultErrorAdapter();
        
        try {
            
        // DTO: body (CreateUserDTO)
        let body: any = {};
        // Map Query
        Object.assign(body, req.query);
        // Map Params
        Object.assign(body, req.params);
        // Map Body
        Object.assign(body, req.body);
        // Map Headers
        Object.assign(body, req.headers);
        // Map Cookies
        Object.assign(body, req.cookies || {});

            const response = await controller.createUser(body);
            res.status(201).json(response);
        } catch (err: any) {
            const transformedError = errorAdapter.handleError(err);
            next(transformedError);
        }
    });
    
    app.put('/api/users/:id', [], async (req: Request, res: Response, next: NextFunction) => {
        const controller = new ExampleController();
        
        // Initialize adapters
        const errorAdapter = new DefaultErrorAdapter();
        
        try {
            
        const id = (req.body as any)?.id || (req.params as any)?.id || (req.query as any)?.id;

        // DTO: body (UpdateUserDTO)
        let body: any = {};
        // Map Query
        Object.assign(body, req.query);
        // Map Params
        Object.assign(body, req.params);
        // Map Body
        Object.assign(body, req.body);
        // Map Headers
        Object.assign(body, req.headers);
        // Map Cookies
        Object.assign(body, req.cookies || {});

            const response = await controller.updateUser(id, body);
            res.status(200).json(response);
        } catch (err: any) {
            const transformedError = errorAdapter.handleError(err);
            next(transformedError);
        }
    });
    
    app.delete('/api/users/:id', [], async (req: Request, res: Response, next: NextFunction) => {
        const controller = new ExampleController();
        
        // Initialize adapters
        const errorAdapter = new DefaultErrorAdapter();
        
        try {
            
        const id = (req.body as any)?.id || (req.params as any)?.id || (req.query as any)?.id;

            const response = await controller.deleteUser(id);
            res.status(204).send();
        } catch (err: any) {
            const transformedError = errorAdapter.handleError(err);
            next(transformedError);
        }
    });
    
    app.get('/api/users/admin/stats', [], async (req: Request, res: Response, next: NextFunction) => {
        const controller = new ExampleController();
        
        // Initialize adapters
        const errorAdapter = new DefaultErrorAdapter();
        
        try {
            
            const response = await controller.getAdminStats();
            res.status(200).json(response);
        } catch (err: any) {
            const transformedError = errorAdapter.handleError(err);
            next(transformedError);
        }
    });
    
}
