/* tslint:disable */
/* eslint-disable */
// WARNING: This file was auto-generated by adorn-api. Do not edit.
import { Express, Request, Response } from 'express';
import { UserListRequest } from './controllers/advanced.controller.js';
import { CreateUserDto } from './controllers/advanced.controller.js';
import { AdvancedController } from './controllers/advanced.controller.js';
import { GetUserRequest } from './controllers/user.controller.js';
import { CreateUserRequest } from './controllers/user.controller.js';
import { UserController } from './controllers/user.controller.js';

export function RegisterRoutes(app: Express) {
    
    app.get('/advanced/:tenantId/users', async (req: Request, res: Response) => {
        const controller = new AdvancedController();
        try {
            
        const input: any = {};
        // Map Query
        Object.assign(input, req.query);
        // Map Params
        Object.assign(input, req.params);
        // Map Body
        Object.assign(input, req.body);
        
        // In a real app, you would run 'zod' or 'class-validator' here on 'input'
      
            const response = await controller.listUsers(input);
            res.status(200).json(response);
        } catch (err: any) {
            console.error(err);
            res.status(500).send(err.message);
        }
    });
    
    app.post('/advanced/', async (req: Request, res: Response) => {
        const controller = new AdvancedController();
        try {
            
        const input: any = {};
        // Map Query
        Object.assign(input, req.query);
        // Map Params
        Object.assign(input, req.params);
        // Map Body
        Object.assign(input, req.body);
        
        // In a real app, you would run 'zod' or 'class-validator' here on 'input'
      
            const response = await controller.create(input);
            res.status(200).json(response);
        } catch (err: any) {
            console.error(err);
            res.status(500).send(err.message);
        }
    });
    
    app.get('/users/:userId', async (req: Request, res: Response) => {
        const controller = new UserController();
        try {
            
        const input: any = {};
        // Map Query
        Object.assign(input, req.query);
        // Map Params
        Object.assign(input, req.params);
        // Map Body
        Object.assign(input, req.body);
        
        // In a real app, you would run 'zod' or 'class-validator' here on 'input'
      
            const response = await controller.getUser(input);
            res.status(200).json(response);
        } catch (err: any) {
            console.error(err);
            res.status(500).send(err.message);
        }
    });
    
    app.post('/users/', async (req: Request, res: Response) => {
        const controller = new UserController();
        try {
            
        const input: any = {};
        // Map Query
        Object.assign(input, req.query);
        // Map Params
        Object.assign(input, req.params);
        // Map Body
        Object.assign(input, req.body);
        
        // In a real app, you would run 'zod' or 'class-validator' here on 'input'
      
            const response = await controller.createUser(input);
            res.status(200).json(response);
        } catch (err: any) {
            console.error(err);
            res.status(500).send(err.message);
        }
    });
    
}
